### ISSUE TITLE
Texy removes data-* attributes

### ISSUE THREAD

**Issue by mhujer** [dg/texy#22]
`data-*` attributes are [allowed in HTML5](http://www.w3.org/TR/html5/dom.html#embedding-custom-non-visible-data-with-the-data-*-attributes) but Texy strips them. Some of them can be allowed manually:
```
$texy->dtd['a'][0]['data-id'] = 1;
$texy->dtd['a'][0]['data-animation'] = 1;
```
But it would be great to have possibility to allow all of them (they are often used in user content to trigger some JS - lightboxes and stuff).

Testcase: https://github.com/mhujer/texy/compare/gh-22?expand=1

Ref: old thread: http://forum.texy.info/cs/887-texy-maze-attributy-napr-data-x

**Comment by mhujer** [comment]
:+1: Thanks!

**Comment by tomasfejfar** [comment]
:+1:

**Comment by medhi** [comment]
`data-*` attribute is still not possible to write down in texy format: `"link .{data-test:coffee}":http://link.com`
It creates `style` parameter.


https://texy.info/en/try/sw1smxda

**Comment by dg** [comment]
Because `.{key:value}` is used for CSS.

**Comment by arcao** [comment]
It's easy to fix, see this commit: https://github.com/arcao/texy/commit/a4c9c284d38eccd3a2ef4466f4f493445a2a3745

**Comment by dg** [comment]
@arcao Ah, only now I realize what @medhi meant. I'll fix it.
