### ISSUE TITLE
possible security violation: allowed XSS for URLs

### ISSUE THREAD

**Issue by iinfo-dev-mk** [dg/texy#31]
example: in http://texy.info/cs/try check safemode  and use this pattern

`<a href="jAvascript://%0d%0aalert('XSS attack');">click me</a>`

I didn't test current github version, but demo must be definitely without any XSS.

**Comment by JanTvrdik** [comment]
sidenote: reproducible on http://editor.nette.org/ as well

**Comment by iinfo-dev-mk** [comment]
Hm, XSS is still there, see #34
